--- # handlers playbookk
- hosts: all
  user: ansible
  become: yes
  connection: ssh

  tasks:
          - name: installing httpd
            action: yum name=httpd state=present
            notify: starting service 

  handlers: 
   
          - name: starting service
            action: service name=httpd state=started




