--- # multi users playbook
- hosts: all
  user: ansible
  become: yes
  connection: ssh


  tasks:
          - name: creating multi users
            user: name='{{item}}' state=present
            with_items:
                    - shaan
                    - suman
                    - satya  


